version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./composer.json:/var/www/html/composer.json
      - ./vendor:/var/www/html/vendor
      - ./logs:/var/www/html/logs
    environment:
      - APP_ENV=development
      # Paynow Configuration
      - PAYNOW_INTEGRATION_ID=${PAYNOW_INTEGRATION_ID}
      - PAYNOW_INTEGRATION_KEY=${PAYNOW_INTEGRATION_KEY}
      - PAYNOW_RESULT_URL=${PAYNOW_RESULT_URL:-http://localhost:8080/payment/update}
      - PAYNOW_RETURN_URL=${PAYNOW_RETURN_URL:-http://localhost:8080/payment/complete}
      - PAYNOW_AUTH_EMAIL=${PAYNOW_AUTH_EMAIL:-test@example.com}
      - PAYNOW_TEST_MODE=${PAYNOW_TEST_MODE:-true}
      # Application URLs
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:8080}
      - APP_SUCCESS_URL=${APP_SUCCESS_URL:-http://localhost:8080/payment/success}
      - APP_ERROR_URL=${APP_ERROR_URL:-http://localhost:8080/payment/error}
      # Debug
      - PRINT_LOGS_TO_TERMINAL=true
    restart: unless-stopped
    env_file:
      - .env 